CREATE TABLE IF NOT EXISTS Battalion (
	BTL INTEGER PRIMARY KEY AUTOINCREMENT,
	騎士団名 TEXT,
	物攻 TINYINT,
	魔攻 TINYINT,
	命中 TINYINT,
	必殺 TINYINT,
	回避 TINYINT,
	防御 TINYINT,
	耐魔 TINYINT,
	計略 TEXT,
	レベル TINYINT,
	戦力 SMALLINT
	)