CREATE TABLE IF NOT EXISTS Class (
	CLS INTEGER PRIMARY KEY AUTOINCREMENT, 
	クラス名 TEXT,
	クラス階級 TINYINT,
	クラス性別 BLOB,
	クラス移動種 TEXT,
	有効 TEXT,
	HP_成長 TINYINT,
	力_成長 TINYINT,
	魔力_成長 TINYINT,
	技_成長 TINYINT,
	速さ_成長 TINYINT,
	幸運_成長 TINYINT,
	守備_成長 TINYINT,
	魔防_成長 TINYINT,
	魅力_成長 TINYINT,
	HP_基礎 TINYINT,
	力_基礎 TINYINT,
	魔力_基礎 TINYINT,
	技_基礎 TINYINT,
	速さ_基礎 TINYINT,
	幸運_基礎 TINYINT,
	守備_基礎 TINYINT,
	魔防_基礎 TINYINT,
	魅力_基礎 TINYINT
	)