SELECT Chara.キャラ名, Class.クラス名, Units.LVL, Units.HP, Units.力, Units.魔力, Units.技, Units.速さ, Units.幸運, Units.守備, Units.魔防, Units.魅力,
--Units.技能_剣術 AS 剣術, Units.技能_槍術 AS 槍術, Units.技能_斧術 AS 斧術, Units.技能_弓術 AS 弓術, Units.技能_格闘術 AS 格闘術, Units.技能_理学 AS 理学, Units.技能_信仰 AS 信仰, Units.技能_指揮 AS 指揮, Units.技能_重装 AS 重装, Units.技能_馬術 AS 馬術, Units.技能_飛行 AS 飛行
	CASE Units.技能_剣術
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 剣術,
	CASE Units.技能_槍術
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 槍術,
	CASE Units.技能_斧術
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 斧術,
	CASE Units.技能_弓術
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 弓術,
	CASE Units.技能_格闘術
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 格闘術,
	CASE Units.技能_理学
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 理学,
	CASE Units.技能_信仰
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 信仰,
	CASE Units.技能_指揮
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 指揮,
	CASE Units.技能_重装
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 重装,
	CASE Units.技能_馬術
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 馬術,
	CASE Units.技能_飛行
		WHEN 1 THEN 'E'
		WHEN 2 THEN 'E+'
		WHEN 3 THEN 'D'
		WHEN 4 THEN 'D+'
		WHEN 5 THEN 'C'
		WHEN 6 THEN 'C+'
		WHEN 7 THEN 'B'
		WHEN 8 THEN 'B+'
		WHEN 9 THEN 'A'
		WHEN 10 THEN 'A+'
		WHEN 11 THEN 'S'
		WHEN 12 THEN 'S+'
	END AS 飛行
	
	FROM CurrentUnits AS Units 
	JOIN Characters AS Chara
	ON Units.CHR = Chara.CHR
	JOIN Class
	ON Units.CLS = Class.CLS